com:
    didispace:
        blog:
            bignumber: ${random.long}
            desc: ${com.didispace.blog.name}正在努力写《${com.didispace.blog.title}》
            name: 程序猿DD
            number: ${random.int}
            test1: ${random.int(10)}
            test2: ${random.int[10,20]}
            title: Spring Boot教程
            value: ${random.value}
spring:
    profiles:
        active: dev